name: Publish to Mirror

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-FUN-500-TLS-5-1-glados-matthieu.fraiz.git
  BINARY: "glados"

jobs:
  compile:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v3

    - name: Permissions bug workaround
      run: |
        chown -R $(id -un):$(id -gn) ~

    - name: compile
      run: |
        timeout 2m make

    - name: check_binary
      run: |
        if [[ ! -f $BINARY ]]; then
          echo "::error title=Executable not found::$BINARY"
        fi

  publish:
    needs: check_binary
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.KEY_GIT_PUSH }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy app
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release-tag: "latest"
          files: glados

