name: Publish to Mirror

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-FUN-500-TLS-5-1-glados-matthieu.fraiz.git
  BINARY: "glados"

jobs:
  compile:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-cache-action@v2

    - name: Permissions bug workaround
      run: |
        chown -R $(id -un):$(id -gn) ~

    - name: compile
      run: |
        timeout 5m make

    - name: check_binary
      run: |
        if [[ ! -f $BINARY ]]; then
          echo "::error title=Executable not found::$BINARY"
        fi

    - uses: actions/upload-artifact@v2
      with:
        name: glados-bin
        path: glados

  publish:
    needs: compile
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.KEY_GIT_PUSH }}

  deploy:
    needs: compile
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: glados-bin

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export DATE=$(date +"%d/%m/%Y_%Hh%M")
          gh release create "$DATE"       \
            --title "Dev build"                 \
            --generate-notes                    \
            --target main                       \
            "$PWD/glados#glados-bin"


