name: Publish to Mirror

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-FUN-500-TLS-5-1-glados-matthieu.fraiz.git
  BINARY: "glados"

jobs:
  compile:
    runs-on: ubuntu-latest
    container: someone2love/glados_build_env:latest

    steps:
    - uses: actions/checkout@v3

    - name: Permissions bug workaround
      run: |
        chown -R $(id -un):$(id -gn) ~

    - name: run_tests
      run: make tests

    - name: compile
      run: |
        make build

    - uses: actions/upload-artifact@v2
      with:
        name: glados-bin
        path: glados

  publish:
    needs: compile
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.KEY_GIT_PUSH }}

  deploy:
    needs: compile
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: glados-bin

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -a
          source glados.env
          set +a
          gh release create "$GLADOS_VERSION"       \
            --title "Glados $GLADOS_VERSION"                 \
            --generate-notes                    \
            --target main                       \
            "$PWD/glados#glados-bin"


